Repository heptastique/onlygo, pull requests merged in 2018-04, with the labels that each got.

#35 Add hibernate property
  pom.xml
Labels: bug

#52 Controller test
  codecov.yml
  docs/endpoints.md
  pom.xml
  src/main/java/smart/Controller/ActivityController.java
  src/main/java/smart/Controller/UserController.java
  src/main/java/smart/DTO/ActivityDTO.java
  src/test/java/test/ApplicationTest.java
  src/test/java/test/Controllers/ActivityControllerTest.java
  src/test/java/test/Controllers/MainControllerTest.java
  src/test/java/test/Controllers/SportControllerTest.java
  src/test/java/test/Controllers/UserControllerTest.java
Labels: tests

#104 Delete /user/all endpoint
  docs/Utilisateurs.md
  src/main/java/smart/Config/WebSecurityConfig.java
  src/main/java/smart/Controller/UserController.java
  src/test/java/test/Controllers/UserControllerTest.java
Labels: REST

#96 Get next activity endpoint
  src/main/java/smart/Algorithms/FindByJour.java
  src/main/java/smart/Algorithms/ProgramActivities.java
  src/main/java/smart/Controller/ActivityController.java
  src/main/java/smart/Entities/Activity.java
  src/main/java/smart/Entities/Programme.java
  src/main/java/smart/Services/ActivityService.java
  src/main/resources/import.sql
  src/test/java/test/Controllers/ActivityControllerTest.java
  src/test/java/test/Controllers/TimeFrameControllerTest.java
Labels: REST

#97 Get programme by date endpoint
  docs/Programmes.md
  src/main/java/smart/Algorithms/ProgramActivities.java
  src/main/java/smart/Controller/ProgrammeController.java
  src/main/java/smart/Repositories/ProgrammeRepository.java
  src/main/java/smart/Services/ProgrammeService.java
  src/main/java/smart/Services/RealisationService.java
  src/test/java/test/Controllers/ProgrammeControllerTest.java
  src/test/java/test/Services/ProgrammeServiceTest.java
Labels: REST
